### ISSUE TITLE
SimpleIndexer crashes permanently after docs with invalid embeddings are indexed

### ISSUE THREAD

**Issue by winstonww** [jina-ai/executor-simpleindexer#32]
In an attempt to address #28 and as discussed in the same issue, we have re-introduced the issue of SimpleIndexer crashing permanently after docs with invalid embeddings are indexed.

**Comment by cristianmtr** [comment]
As discussed in Hub Alignment, this is not something we will tackle with something from the Indexer itself. It's up to the upstream to filter out invalid docs at the earliest stage.

**Comment by winstonww** [comment]
I think filtering from upstream is a good practice but does not really fix this issue, as there is really no guarantee that (all) users will not index docs with invalid embeddings. If it's possible to add docs with invalid embeddings to the index, that means it is still an issue. I propose we keep this issue open to keep track of things instead of dismissing it as something we have already fixed.

**Comment by cristianmtr** [comment]
Let's move this discussion to [slack](https://jinaai.slack.com/archives/C02AC4T8Y5T/p1636366835223100)

**Comment by nan-wang** [comment]
We decide to not check this in the SimpleIndexer
